version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: chatple-postgres-db
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chatple-network

  chatple-server:
    build: .
    container_name: chatple-server-app
    ports:
      - "2086:3000"
    networks:
      - chatple-network
    env_file:
      - .env
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - PORT=3000
      - NODE_ENV=development

networks:
  chatple-network:
    driver: bridge

volumes:
  postgres_data:
